--- #YAML:1.0
name:               MySQL-Privilege-Reader
version:            0.01
abstract:           Determines which privileges are valid for a given MySQL Database Connection
author:
    - Luis Motta Campos <lmc@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Exception:   0.29
    Test::MockObject:  1.09
    Test::More:        0
requires:
    Test::Exception:   0.29
    Test::MockObject:  1.09
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
